### PR TITLE
Added a now choke and made it to comply with KLC

### PR DESCRIPTION
**Pull request by crackerizer**

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Hello @crackerizer, please re-save the files using Kicad. Do you submit the 3d models as well? If so, could you please link the pull request here? Thanks.

**Comment by crackerizer** [comment]
Hello, I've removed 3d model from the footprint, saved from Kicad.

**Comment by ricardocrudo** [comment]
Silkscreen of Choke_Toroid_15x40mm_Horizontal is superposing pads.

**Comment by jkriege2** [comment]
Hi!

this repo has been deprecatd. Please resubmit you PR to the new SMD/THT-inductors repo, using the naming standard used there:
https://github.com/KiCad/Inductors_SMD.pretty
https://github.com/KiCad/Inductors_THT.pretty

Best,
 JAN

**Comment by SchrodingersGat** [comment]
@crackerizer I am closing this PR as this repository is deprecated and no longer accepting PRs. Please resubmit this to one of the new Inductor libraries as @jkriege2  has listed above :)

**Pull request closed without merging**
